### ISSUE TITLE
lost casambi light entities.

### ISSUE THREAD

**Issue by hw76** [hellqvio86/home_assistant_casambi#47]
Every day a few times  HASS loses ithe casambi light entities.

Reloading the integrations does not fix the problem.
The entity status is set on a exclamation mark with a rounded arrow cirkle.

I cannot get the integration working anymore and to fix it the only solution is to restore an old backup.

What is a solution for this?

From the HASS CORE log:
2022-06-13 19:19:37 WARNING (MainThread) [homeassistant.components.light] Setup of light platform casambi is taking over 10 seconds.
2022-06-13 19:19:37 ERROR (MainThread) [custom_components.casambi.light] Error connecting to the Casambi

![image](https://user-images.githubusercontent.com/105842954/173414237-b1313a63-3a96-44f0-9e1f-07e1f1d10f7e.png)

**Comment by hellqvio86** [comment]
Hi,
Please provide debug logs, you probably have Internet connectivity issues, that's my guess.

**Comment by hw76** [comment]
> Hi, Please provide debug logs and screenshot(s), you probably have Internet connectivity issues, that's my guess.

done

**Comment by hellqvio86** [comment]
Please set it to debug mode, 
```
logger:
  default: info
  logs:
    homeassistant.components.casambi: debug
    custom_components.casambi: debug
    aiocasambi: debug
```
